name: publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_TASKLIST }}

      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/rubenmantilladev/tasklist:latest
          docker push ghcr.io/rubenmantilladev/tasklist:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into Server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -p${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
            cd /root/rubenmantilladev/tasklist
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN_TASKLIST }}
            docker pull ghcr.io/rubenmantilladev/tasklist:latest
            docker stop tasklist && docker rm tasklist
            docker run -d \
              --name tasklist \
              -p 80:80 \
              -v /root/rubenmantilladev/tasklist:/app \
              -w /app \
              --restart=always \
              ghcr.io/rubenmantilladev/tasklist:latest
          EOF
